chore: enhance code readability
lumapps/metrx pull request #4
Opened 2018-10-03 08:18 UTC by mcastagnetti

Enhance code readability and simplifies logic.

2018-10-03 09:16 UTC, arnaudvalle requested changes
A few tiny details but overall looks good 👍

2018-10-03 09:16 UTC, arnaudvalle commented on cli.js
> +        start(program, errorHandler).then(output => {
Can we simplify to `then(output => console.log)`?

2018-10-03 09:16 UTC, arnaudvalle commented on js/output.js
> +        RELEVANT_STATS.map(stat => {
Could also be simplified to `(stat => chalk.blue)`?

2018-10-03 09:16 UTC, arnaudvalle commented on js/utils.js
> + * @returns {string} The redable value.
typo: `readable`

2018-10-03 09:16 UTC, arnaudvalle commented on js/utils.js
> + * Makes the diff between a time and the navigation start to get a useable time in ms.
typo: `usable`

2018-10-03 09:16 UTC, arnaudvalle commented on js/utils.js
> + * @param  {integer} time            The time we want the metric from
`.` 💋

2018-10-03 09:16 UTC, arnaudvalle commented on js/utils.js
> +    return metrics.reduce((obj, item) => {
Nice

2018-10-09 08:13 UTC, mcastagnetti commented on cli.js
> +        start(program, errorHandler).then(output => {
Doesn't seems to work :thinking:

2018-10-09 08:14 UTC, merged